"""Deterministic Markdown reference generator for the `mt` CLI.

Walks the Click command tree exposed by Typer and renders every command and
option to Markdown, reading only static attributes (never `get_help()` or
`get_usage()`, which wrap to the terminal width). The output is byte-stable
across machines and terminal sizes, so a test can diff it against the committed
`docs/CLI.md` (see tests/test_docs.py).
"""

from __future__ import annotations

PROG = "mt"

# Completion/help options Typer injects; not part of the app's real surface.
_SKIP_OPTS = {"--help", "--install-completion", "--show-completion"}

_HEADER = (
    "# mt CLI reference\n"
    "<!-- Auto-generated by `mt docs`. Do not edit by hand; "
    "run `uv run mt docs` to regenerate. -->\n"
)


def _cell(text: str | None) -> str:
    """Make a string safe for a Markdown table cell."""
    if not text:
        return ""
    return " ".join(str(text).split()).replace("|", "\\|")


def _visible_params(cmd) -> list:
    return [
        p
        for p in cmd.params
        if not getattr(p, "hidden", False) and not (set(p.opts) & _SKIP_OPTS)
    ]


def _arg_metavar(param) -> str:
    core = param.metavar or param.opts[0].upper()
    if not param.required:
        core = f"[{core}]"
    if param.nargs == -1:
        core = f"{core}..."
    return core


def _format_default(param) -> str:
    if getattr(param, "is_flag", False):
        return "true" if param.default else "false"
    if param.required:
        return "required"
    if param.default is None:
        return ""
    return f"`{param.default}`"


def _options_table(options: list) -> list[str]:
    lines = ["| Option | Default | Description |", "| --- | --- | --- |"]
    for p in options:
        names = ", ".join(f"`{o}`" for o in p.opts)
        if p.secondary_opts:  # boolean flag pair, e.g. --rs3 / --no-rs3
            names += " / " + ", ".join(f"`{o}`" for o in p.secondary_opts)
        lines.append(f"| {names} | {_cell(_format_default(p))} | {_cell(p.help)} |")
    return lines


def _arguments_table(arguments: list) -> list[str]:
    lines = ["| Argument | Required | Description |", "| --- | --- | --- |"]
    for p in arguments:
        req = "yes" if p.required else "no"
        lines.append(f"| `{p.opts[0].upper()}` | {req} | {_cell(p.help)} |")
    return lines


def _command_section(cmd, path: list[str], out: list[str]) -> None:
    params = _visible_params(cmd)
    arguments = [p for p in params if p.param_type_name == "argument"]
    options = [p for p in params if p.param_type_name == "option"]

    usage = " ".join(path)
    if options:
        usage += " [OPTIONS]"
    for p in arguments:
        usage += f" {_arg_metavar(p)}"

    out.append(f"## {' '.join(path)}\n")
    out.append(f"    {usage}\n")
    if cmd.help:
        out.append(f"{cmd.help}\n")
    if arguments:
        out.extend(_arguments_table(arguments))
        out.append("")
    if options:
        out.extend(_options_table(options))
        out.append("")


def _walk(cmd, path: list[str], out: list[str]) -> None:
    subcommands = getattr(cmd, "commands", None)
    if subcommands:
        # A group: emit its own section (help + how to reach sub-commands),
        # then recurse into children sorted by name for a stable ordering.
        if len(path) > 1:  # skip the root app; it is rendered in the header
            out.append(f"## {' '.join(path)}\n")
            if cmd.help:
                out.append(f"{cmd.help}\n")
        for name in sorted(subcommands):
            _walk(subcommands[name], path + [name], out)
    else:
        _command_section(cmd, path, out)


def iter_command_paths() -> list[str]:
    """Every runnable command path, e.g. ['ingest', ..., 'camera list', ...].

    The machine-readable twin of docs/CLI.md: both walk the same command tree,
    so anything asserted against this list is asserted against the documented
    CLI surface. Groups (`camera`, `telemetry`) are not themselves runnable and
    are not included - only their leaf sub-commands are.
    """
    import typer.main

    from .cli import app

    root = typer.main.get_command(app)
    paths: list[str] = []

    def walk(cmd, path: list[str]) -> None:
        subcommands = getattr(cmd, "commands", None)
        if subcommands:
            for name in sorted(subcommands):
                walk(subcommands[name], path + [name])
        else:
            paths.append(" ".join(path))

    for name in sorted(root.commands):
        walk(root.commands[name], [name])
    return paths


def generate_cli_docs() -> str:
    """Render the full CLI reference as Markdown (LF newlines, byte-stable)."""
    import typer.main

    from .cli import app

    root = typer.main.get_command(app)

    out: list[str] = [_HEADER]
    if root.help:
        out.append(f"{root.help}\n")

    global_opts = [p for p in _visible_params(root) if p.param_type_name == "option"]
    if global_opts:
        out.append("## Global options\n")
        out.extend(_options_table(global_opts))
        out.append("")

    for name in sorted(root.commands):
        _walk(root.commands[name], [PROG, name], out)

    return "\n".join(out).rstrip("\n") + "\n"
